# Generated by Django 4.2.1 on 2023-07-12 23:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawpatron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('tipodeal', models.CharField(blank=True, max_length=50, verbose_name='Tipo de alimento')),
                ('tmascot', models.CharField(blank=True, max_length=50, verbose_name='Para:')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpatron.alimentos')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pawpatron.boleta')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpatron.alimentos')),
            ],
        ),
        migrations.AddField(
            model_name='alimentos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpatron.categoria', verbose_name='Categoría'),
        ),
    ]
