# Generated by Django 4.2.1 on 2023-07-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpatron', '0003_alter_boleta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
